// data-vocab.js
// Données nettoyées et formatées à partir de vocabulaire.txt

const VOCAB = [
  // Noms (nom)
  { german: "Mann", french: "l’homme", type: "nom", gender: "m" },
  { german: "Frau", french: "la femme", type: "nom", gender: "f" },
  { german: "Kind", french: "l’enfant", type: "nom", gender: "n" },
  { german: "Mensch", french: "l’être humain", type: "nom", gender: "m" },
  { german: "Leute", french: "les gens", type: "nom (pl)", gender: "pl" },
  { german: "Familie", french: "la famille", type: "nom", gender: "f" },
  { german: "Leben", french: "la vie", type: "nom", gender: "n" },
  { german: "Zeit", french: "le temps", type: "nom", gender: "f" },
  { german: "Jahr", french: "l’année", type: "nom", gender: "n" },
  { german: "Tag", french: "le jour", type: "nom", gender: "m" },
  { german: "Woche", french: "la semaine", type: "nom", gender: "f" },
  { german: "Monat", french: "le mois", type: "nom", gender: "m" },
  { german: "Anzug", french: "le costume", type: "nom", gender: "m" },
  { german: "Fabrik", french: "l'usine", type: "nom", gender: "f" },
  { german: "Stadt", french: "la ville", type: "nom", gender: "f" },
  { german: "Land", french: "le pays", type: "nom", gender: "n" },
  { german: "Halb", french: "la moitié", type: "nom", gender: "n" },
  { german: "Name", french: "le nom", type: "nom", gender: "m" },
  { german: "Sprache", french: "la langue", type: "nom", gender: "f" },
  { german: "Fachrichtung", french: "la spécialité", type: "nom", gender: "f" },
  { german: "Wort", french: "le mot", type: "nom", gender: "n" },
  { german: "Satz", french: "la phrase", type: "nom", gender: "m" },
  { german: "Buch", french: "le livre", type: "nom", gender: "n" },
  { german: "Schule", french: "l’école", type: "nom", gender: "f" },
  { german: "Rechnung", french: "la facture", type: "nom", gender: "f" },
  { german: "Ticket", french: "le ticket", type: "nom", gender: "n" },
  { german: "Geräusch", french: "le bruit", type: "nom", gender: "n" },
  { german: "Bitte", french: "la demande", type: "nom", gender: "f" },
  { german: "Karte", french: "la carte", type: "nom", gender: "f" },
  { german: "Möglichkeit", french: "la possibilité", type: "nom", gender: "f" },
  { german: "Kalender", french: "le calendrier", type: "nom", gender: "m" },
  { german: "Universität", french: "l’université", type: "nom", gender: "f" },
  { german: "Lehrer", french: "le professeur", type: "nom", gender: "m" },
  { german: "Lehrerin", french: "la professeure", type: "nom", gender: "f" },
  { german: "Schüler", french: "l’élève (masculin)", type: "nom", gender: "m" },
  { german: "Inner", french: "l'intérieur", type: "nom", gender: "n" },
  { german: "Schülerin", french: "l’élève (féminin)", type: "nom", gender: "f" },
  { german: "Freund", french: "l’ami", type: "nom", gender: "m" },
  { german: "Sieg", french: "la victoire", type: "nom", gender: "m" },
  { german: "Freundin", french: "l’amie", type: "nom", gender: "f" },
  { german: "Auto", french: "la voiture", type: "nom", gender: "n" },
  { german: "Datei", french: "le fichier", type: "nom", gender: "f" },
  { german: "Datum", french: "la donnée / la date", type: "nom", gender: "n" },
  { german: "Unwetter", french: "les intempéries", type: "nom", gender: "n" },
  { german: "Bergtour", french: "une excursion en montagne", type: "nom", gender: "f" },
  { german: "Haus", french: "la maison", type: "nom", gender: "n" },
  { german: "Tisch", french: "la table", type: "nom", gender: "m" },
  { german: "Stuhl", french: "la chaise", type: "nom", gender: "m" },
  { german: "Tür", french: "la porte", type: "nom", gender: "f" },
  { german: "Fenster", french: "la fenêtre", type: "nom", gender: "n" },
  { german: "Glückwunsch", french: "félicitation", type: "nom", gender: "m" },
  { german: "Geld", french: "l’argent", type: "nom", gender: "n" },
  { german: "Euro", french: "l’euro", type: "nom", gender: "m" },
  { german: "Stunde", french: "l'heure", type: "nom", gender: "f" },
  { german: "Schauspieler", french: "l'acteur", type: "nom", gender: "m" },
  { german: "Uhr", french: "la montre / l’heure", type: "nom", gender: "f" },
  { german: "Essen", french: "la nourriture", type: "nom", gender: "n" },
  { german: "Trinken", french: "la boisson", type: "nom", gender: "n" },
  { german: "Vater", french: "le père", type: "nom", gender: "m" },
  { german: "Mutter", french: "la mère", type: "nom", gender: "f" },
  { german: "Hand", french: "la main", type: "nom", gender: "f" },
  { german: "Welt", french: "le monde", type: "nom", gender: "f" },
  { german: "Werkzeug", french: "l'outil", type: "nom", gender: "n" },
  { german: "Niederlage", french: "la défaite", type: "nom", gender: "f" },
  { german: "Platz", french: "la place", type: "nom", gender: "m" },
  { german: "Beispiel", french: "l’exemple", type: "nom", gender: "n" },
  { german: "Morgen", french: "le matin", type: "nom", gender: "m" },
  { german: "Wasser", french: "l’eau", type: "nom", gender: "n" },
  { german: "Katze", french: "le chat", type: "nom", gender: "f" },
  { german: "Bär", french: "l'ours", type: "nom", gender: "m" },
  { german: "Zelt", french: "la tente", type: "nom", gender: "n" },
  { german: "Metzger", french: "le boucher", type: "nom", gender: "m" },
  { german: "Kaninchen", french: "le lapin", type: "nom", gender: "n" },
  { german: "Spiegel", french: "le miroir", type: "nom", gender: "m" },
  { german: "Hund", french: "le chien", type: "nom", gender: "m" },
  { german: "Lächeln", french: "le sourire", type: "nom", gender: "n" },
  { german: "Glück", french: "le bonheur", type: "nom", gender: "n" },
  { german: "Liebe", french: "l’amour", type: "nom", gender: "f" },
  { german: "Fahrrad", french: "le vélo", type: "nom", gender: "n" },
  { german: "Bahn", french: "le train", type: "nom", gender: "f" },
  { german: "Alternative", french: "l'alternative", type: "nom", gender: "f" },
  { german: "Wahl", french: "l'option", type: "nom", gender: "f" },
  { german: "Brief", french: "la lettre", type: "nom", gender: "m" },
  { german: "Zimmer", french: "la chambre / pièce", type: "nom", gender: "n" },
  { german: "Boden", french: "le sol", type: "nom", gender: "m" },
  { german: "Decke", french: "le plafond / la couverture", type: "nom", gender: "f" },
  { german: "Wand", french: "le mur", type: "nom", gender: "f" },
  { german: "Straße", french: "la rue", type: "nom", gender: "f" },
  { german: "Weg", french: "le chemin", type: "nom", gender: "m" },
  { german: "Berg", french: "la montagne", type: "nom", gender: "m" },
  { german: "Baum", french: "l’arbre", type: "nom", gender: "m" },
  { german: "Blume", french: "la fleur", type: "nom", gender: "f" },
  { german: "Wald", french: "la forêt", type: "nom", gender: "m" },
  { german: "Himmel", french: "le ciel", type: "nom", gender: "m" },
  { german: "Stern", french: "l’étoile", type: "nom", gender: "m" },
  { german: "Sonne", french: "le soleil", type: "nom", gender: "f" },
  { german: "Mond", french: "la lune", type: "nom", gender: "m" },
  { german: "Feuer", french: "le feu", type: "nom", gender: "n" },
  { german: "Luft", french: "l’air", type: "nom", gender: "f" },
  { german: "Erde", french: "la terre", type: "nom", gender: "f" },
  { german: "Sand", french: "le sable", type: "nom", gender: "m" },
  { german: "Stein", french: "la pierre", type: "nom", gender: "m" },
  { german: "Gold", french: "l’or", type: "nom", gender: "n" },
  { german: "Silber", french: "l’argent (métal)", type: "nom", gender: "n" },
  { german: "Glas", french: "le verre", type: "nom", gender: "n" },
  { german: "Holz", french: "le bois", type: "nom", gender: "n" },
  { german: "Papier", french: "le papier", type: "nom", gender: "n" },
  { german: "Bild", french: "l’image / le tableau", type: "nom", gender: "n" },
  { german: "Laden", french: "le magasin", type: "nom", gender: "m" },
  { german: "Einkaufszentrum", french: "le centre commercial", type: "nom", gender: "n" },
  { german: "Dienst", french: "le service", type: "nom", gender: "m" },
  { german: "Kellner", french: "le serveur", type: "nom", gender: "m" },
  { german: "Film", french: "le film", type: "nom", gender: "m" },
  { german: "Musik", french: "la musique", type: "nom", gender: "f" },
  { german: "Lied", french: "la chanson", type: "nom", gender: "n" },
  { german: "Ausgang", french: "la sortie", type: "nom", gender: "m" },
  { german: "Eintrag", french: "l'entrée", type: "nom", gender: "m" },
  { german: "Kunst", french: "l’art", type: "nom", gender: "f" },
  { german: "Frage", french: "la question", type: "nom", gender: "f" },
  { german: "Antwort", french: "la réponse", type: "nom", gender: "f" },
  { german: "Idee", french: "l’idée", type: "nom", gender: "f" },
  { german: "Gedanke", french: "la pensée", type: "nom", gender: "m" },
  { german: "Gefühl", french: "le sentiment", type: "nom", gender: "n" },
  { german: "Angst", french: "la peur", type: "nom", gender: "f" },
  { german: "Hoffnung", french: "l’espoir", type: "nom", gender: "f" },
  { german: "Raum", french: "l'espace", type: "nom", gender: "m" },
  { german: "Freiheit", french: "la liberté", type: "nom", gender: "f" },
  { german: "Topf", french: "la casserole", type: "nom", gender: "m" },
  { german: "Frieden", french: "la paix", type: "nom", gender: "m" },
  { german: "Krieg", french: "la guerre", type: "nom", gender: "m" },
  { german: "Arzt", french: "le médecin", type: "nom", gender: "m" },
  { german: "Ärztin", french: "la médecin", type: "nom", gender: "f" },
  { german: "Krankenhaus", french: "l’hôpital", type: "nom", gender: "n" },
  { german: "Beschreibung", french: "la description", type: "nom", gender: "f" },
  { german: "Muttersprache", french: "la langue maternelle", type: "nom", gender: "f" },
  { german: "Patient", french: "le patient", type: "nom", gender: "m" },
  { german: "Gesundheit", french: "la santé", type: "nom", gender: "f" },
  { german: "Problem", french: "le problème", type: "nom", gender: "n" },
  { german: "Lösung", french: "la solution", type: "nom", gender: "f" },
  { german: "Wissen", french: "le savoir", type: "nom", gender: "n" },
  { german: "Natur", french: "la nature", type: "nom", gender: "f" },
  { german: "Tier", french: "l’animal", type: "nom", gender: "n" },
  { german: "Vogel", french: "l’oiseau", type: "nom", gender: "m" },
  { german: "Fisch", french: "le poisson", type: "nom", gender: "m" },
  { german: "Insekt", french: "l’insecte", type: "nom", gender: "n" },
  { german: "Version", french: "la version", type: "nom", gender: "f" },
  { german: "Ton", french: "le ton", type: "nom", gender: "m" },
  { german: "Biene", french: "l’abeille", type: "nom", gender: "f" },
  { german: "Kuh", french: "la vache", type: "nom", gender: "f" },
  { german: "Schwein", french: "le cochon", type: "nom", gender: "n" },
  { german: "Pferd", french: "le cheval", type: "nom", gender: "n" },
  { german: "Huhn", french: "la poule", type: "nom", gender: "n" },
  { german: "Ei", french: "l’œuf", type: "nom", gender: "n" },
  { german: "Brot", french: "le pain", type: "nom", gender: "n" },
  { german: "Butter", french: "le beurre", type: "nom", gender: "f" },
  { german: "Käse", french: "le fromage", type: "nom", gender: "m" },
  { german: "Obst", french: "les fruits", type: "nom", gender: "n" },
  { german: "Gemüse", french: "les légumes", type: "nom", gender: "n" },
  { german: "Apfel", french: "la pomme", type: "nom", gender: "m" },
  { german: "Banane", french: "la banane", type: "nom", gender: "f" },
  { german: "Orange", french: "l’orange", type: "nom", gender: "f" },
  { german: "Tomate", french: "la tomate", type: "nom", gender: "f" },
  { german: "Kartoffel", french: "la pomme de terre", type: "nom", gender: "f" },
  { german: "Zwiebel", french: "l’oignon", type: "nom", gender: "f" },
  { german: "Traum", french: "le rêve", type: "nom", gender: "m" },
  { german: "Grund", french: "la raison", type: "nom", gender: "m" },
  { german: "Albtraum", french: "le cauchemar", type: "nom", gender: "m" },
  { german: "Maler", french: "le peintre", type: "nom", gender: "m" },
  { german: "Malen", french: "la peinture", type: "nom", gender: "n" },
  { german: "Künstler", french: "l'artiste", type: "nom", gender: "m" },
  { german: "Erfahrung", french: "l’expérience", type: "nom", gender: "f" },
  { german: "Zukunft", french: "le futur", type: "nom", gender: "f" },
  { german: "Vergangenheit", french: "le passé", type: "nom", gender: "f" },
  { german: "Gegenwart", french: "le présent", type: "nom", gender: "f" },
  { german: "Plan", french: "le plan", type: "nom", gender: "m" },
  { german: "Ziel", french: "le but", type: "nom", gender: "n" },
  { german: "Erfolg", french: "le succès", type: "nom", gender: "m" },
  { german: "Fehler", french: "l’erreur", type: "nom", gender: "m" },
  { german: "Unfall", french: "l’accident", type: "nom", gender: "m" },
  { german: "Karotte", french: "la carotte", type: "nom", gender: "f" },
  { german: "Gurke", french: "le concombre", type: "nom", gender: "f" },
  { german: "Knoblauch", french: "l’ail", type: "nom", gender: "m" },
  { german: "Paprika", french: "le poivron", type: "nom", gender: "m" },
  { german: "Kleidungsstück", french: "le vêtement", type: "nom", gender: "n" },
  { german: "Kleidung", french: "l'habille", type: "nom", gender: "f" },
  { german: "Mantel", french: "le manteau", type: "nom", gender: "m" },
  { german: "Hose", french: "le pantalon", type: "nom", gender: "f" },
  { german: "Hemd", french: "la chemise", type: "nom", gender: "n" },
  { german: "Socke", french: "la chaussette", type: "nom", gender: "f" },
  { german: "Brille", french: "les lunettes", type: "nom", gender: "f" },
  { german: "Zweig", french: "la branche", type: "nom", gender: "m" },
  { german: "Überlegung", french: "le raisonnement", type: "nom", gender: "f" },
  { german: "Wunsch", french: "le souhait", type: "nom", gender: "m" },
  { german: "Blumenkohl", french: "le chou-fleur", type: "nom", gender: "m" },
  { german: "Kirche", french: "l'église", type: "nom", gender: "f" },
  { german: "Pfanne", french: "la poêle", type: "nom", gender: "f" },
  { german: "Küche", french: "la cuisine", type: "nom", gender: "f" },
  { german: "Ofen", french: "le four", type: "nom", gender: "m" },
  { german: "Brokkoli", french: "le brocoli", type: "nom", gender: "m" },
  { german: "Spinat", french: "les épinards", type: "nom", gender: "m" },
  { german: "Erbse", french: "le pois", type: "nom", gender: "f" },
  { german: "Bohne", french: "le haricot", type: "nom", gender: "f" },
  { german: "Kürbis", french: "la courge / le potiron", type: "nom", gender: "m" },
  { german: "Lauch", french: "le poireau", type: "nom", gender: "m" },
  { german: "Sellerie", french: "le céleri", type: "nom", gender: "m" },
  { german: "Rote Bete", french: "la betterave", type: "nom", gender: "f" },
  { german: "Aubergine", french: "l’aubergine", type: "nom", gender: "f" },
  { german: "Zucchini", french: "la courgette", type: "nom", gender: "f" },
  { german: "Artischocke", french: "l’artichaut", type: "nom", gender: "f" },
  { german: "Mais", french: "le maïs", type: "nom", gender: "m" },
  { german: "Pilz", french: "le champignon", type: "nom", gender: "m" },
  { german: "Birne", french: "la poire", type: "nom", gender: "f" },
  { german: "Mandarine", french: "la mandarine", type: "nom", gender: "f" },
  { german: "Zitrone", french: "le citron", type: "nom", gender: "f" },
  { german: "Pfirsich", french: "la pêche", type: "nom", gender: "m" },
  { german: "Aprikose", french: "l’abricot", type: "nom", gender: "f" },
  { german: "Kirsche", french: "la cerise", type: "nom", gender: "f" },
  { german: "Traube", french: "le raisin", type: "nom", gender: "f" },
  { german: "Melone", french: "le melon", type: "nom", gender: "f" },
  { german: "Wassermelone", french: "la pastèque", type: "nom", gender: "f" },
  { german: "Erdbeere", french: "la fraise", type: "nom", gender: "f" },
  { german: "Himbeere", french: "la framboise", type: "nom", gender: "f" },
  { german: "Brombeere", french: "la mûre", type: "nom", gender: "f" },
  { german: "Heidelbeere", french: "la myrtille", type: "nom", gender: "f" },
  { german: "Ananas", french: "l’ananas", type: "nom", gender: "f" },
  { german: "Kiwi", french: "le kiwi", type: "nom", gender: "f" },
  { german: "Pflaume", french: "la prune", type: "nom", gender: "f" },
  { german: "Granatapfel", french: "la grenade", type: "nom", gender: "m" },
  { german: "Feige", french: "la figue", type: "nom", gender: "f" },
  { german: "Schwierigkeit", french: "la difficulté", type: "nom", gender: "f" },
  { german: "Dattel", french: "la datte", type: "nom", gender: "f" },
  { german: "Mango", french: "la mangue", type: "nom", gender: "f" },
  { german: "Papaya", french: "la papaye", type: "nom", gender: "f" },
  { german: "Kokosnuss", french: "la noix de coco", type: "nom", gender: "f" },
  { german: "Haar", french: "le cheveu", type: "nom", gender: "n" },
  { german: "Nase", french: "le nez", type: "nom", gender: "f" },
  { german: "Zahn", french: "la dent", type: "nom", gender: "m" },
  { german: "Schrank", french: "l'armoire", type: "nom", gender: "m" },
  { german: "Zunge", french: "la langue", type: "nom", gender: "f" },
  { german: "Hals", french: "le cou", type: "nom", gender: "m" },
  { german: "Allianz", french: "l'alliance", type: "nom", gender: "f" },
  { german: "Schulter", french: "l’épaule", type: "nom", gender: "f" },
  { german: "Arm", french: "le bras", type: "nom", gender: "m" },
  { german: "Computer", french: "l'ordinateur", type: "nom", gender: "m" },
  { german: "Toilette", french: "les toilettes", type: "nom", gender: "f" },
  { german: "Badezimmer", french: "la salle de bain", type: "nom", gender: "n" },
  { german: "Dusche", french: "la douche", type: "nom", gender: "f" },
  { german: "Brett", french: "la planche", type: "nom", gender: "n" },
  { german: "Ellenbogen", french: "le coude", type: "nom", gender: "m" },
  { german: "Mütze", french: "le chapeau", type: "nom", gender: "f" },
  { german: "Brust", french: "la poitrine", type: "nom", gender: "f" },
  { german: "Rücken", french: "le dos", type: "nom", gender: "m" },
  { german: "Bauch", french: "le ventre", type: "nom", gender: "m" },
  { german: "Bein", french: "la jambe", type: "nom", gender: "n" },
  { german: "Knie", french: "le genou", type: "nom", gender: "n" },
  { german: "Zehe", french: "l’orteil", type: "nom", gender: "f" },
  { german: "Wohlstand", french: "la prospérité", type: "nom", gender: "m" },
  { german: "Lunge", french: "le poumon", type: "nom", gender: "f" },
  { german: "Magen", french: "l’estomac", type: "nom", gender: "m" },
  { german: "Haut", french: "la peau", type: "nom", gender: "f" },
  { german: "Vorwurf", french: "l'accusation", type: "nom", gender: "m" },
  { german: "Steuerberater", french: "conseiller fiscal", type: "nom", gender: "m" },
  { german: "Berater", french: "le conseiller", type: "nom", gender: "m" },
  { german: "Steuer", french: "les taxes", type: "nom", gender: "f" },
  { german: "Säule", french: "le pilier", type: "nom", gender: "f" },
  { german: "Vorhängeschloss", french: "le cadenas", type: "nom", gender: "n" },
  { german: "Bewässerungsanlage", french: "le système d'irrigation", type: "nom", gender: "f" },
  { german: "Hängematte", french: "le hamac", type: "nom", gender: "f" },
  { german: "Salbe", french: "la pommade", type: "nom", gender: "f" },
  { german: "Bettdecke", french: "la couette", type: "nom", gender: "f" },
  { german: "Vetter", french: "le cousin", type: "nom", gender: "m" },
  { german: "Tasche", french: "un sac", type: "nom", gender: "f" },
  { german: "Handtasche", french: "un sac à main", type: "nom", gender: "f" },
  { german: "Rucksack", french: "un sac à dos", type: "nom", gender: "m" },
  { german: "Knochen", french: "l’os", type: "nom", gender: "m" },
  { german: "Muskel", french: "le muscle", type: "nom", gender: "m" },
  { german: "Gefahr", french: "le danger", type: "nom", gender: "f" },
  { german: "Löffel", french: "la cuillère", type: "nom", gender: "m" },
  { german: "Gabel", french: "la fourchette", type: "nom", gender: "f" },
  { german: "Blick", french: "le regard", type: "nom", gender: "m" },
  { german: "Messer", french: "le couteau", type: "nom", gender: "n" },
  { german: "Stift", french: "le stylo", type: "nom", gender: "m" },
  { german: "Heft", french: "le cahier", type: "nom", gender: "n" },
  { german: "Sicherheit", french: "la sécurité", type: "nom", gender: "f" },
  { german: "Seite", french: "la page", type: "nom", gender: "f" },
  { german: "Wahrheit", french: "la vérité", type: "nom", gender: "f" },
  { german: "Lüge", french: "le mensonge", type: "nom", gender: "f" },
  { german: "Größe", french: "la taille", type: "nom", gender: "f" },
  { german: "Fragestellung", french: "le questionnement", type: "nom", gender: "f" },
  { german: "Erdgeschoss", french: "le rez-de-chaussée", type: "nom", gender: "n" },
  { german: "Etage", french: "l'étage", type: "nom", gender: "f" },
  { german: "Geschenk", french: "le cadeau", type: "nom", gender: "n" },
  { german: "Geburtstag", french: "l’anniversaire", type: "nom", gender: "m" },
  { german: "Feier", french: "la fête", type: "nom", gender: "f" },
  { german: "Urlaub", french: "les vacances", type: "nom", gender: "m" },
  { german: "Förderung", french: "la promotion", type: "nom", gender: "f" },
  { german: "Kauf", french: "l'achat", type: "nom", gender: "m" },
  { german: "Qualität", french: "la qualité", type: "nom", gender: "f" },
  { german: "Detail", french: "le détail", type: "nom", gender: "n" },
  { german: "Dokumentation", french: "la documentation", type: "nom", gender: "f" },
  { german: "Barriere", french: "la barrière", type: "nom", gender: "f" },
  { german: "Zaun", french: "la clôture", type: "nom", gender: "m" },
  { german: "Reise", french: "le voyage", type: "nom", gender: "f" },
  { german: "Ausflug", french: "l’excursion", type: "nom", gender: "m" },
  { german: "Strand", french: "la plage", type: "nom", gender: "m" },
  { german: "Meer", french: "la mer", type: "nom", gender: "n" },
  { german: "Übersetzung", french: "la traduction", type: "nom", gender: "f" },
  { german: "Handy", french: "le téléphone portable", type: "nom", gender: "n" },
  { german: "Internet", french: "l’internet", type: "nom", gender: "n" },
  { german: "Herausforderung", french: "le défi", type: "nom", gender: "f" },
  { german: "Stellung", french: "une position", type: "nom", gender: "f" },
  { german: "Ausnahme", french: "l'exception", type: "nom", gender: "f" },
  { german: "Angriff", french: "l'attaque", type: "nom", gender: "m" },
  { german: "Verteidigung", french: "la défense", type: "nom", gender: "f" },
  { german: "Tod", french: "la mort", type: "nom", gender: "m" },
  { german: "Geburt", french: "la naissance", type: "nom", gender: "f" },
  { german: "Bahnhof", french: "la gare", type: "nom", gender: "m" },
  { german: "Flughafen", french: "l'aéroport", type: "nom", gender: "m" },
  { german: "Kurs", french: "le cours", type: "nom", gender: "m" },
  { german: "Mitleid", french: "la pitié", type: "nom", gender: "n" },
  { german: "Vorurteil", french: "le préjugé", type: "nom", gender: "n" },
  { german: "Adler", french: "l'aigle", type: "nom", gender: "m" },
  { german: "Bildschirm", french: "l’écran", type: "nom", gender: "m" },
  { german: "Tastatur", french: "le clavier", type: "nom", gender: "f" },
  { german: "Maus", french: "la souris", type: "nom", gender: "f" },
  { german: "Programm", french: "le programme", type: "nom", gender: "n" },
  { german: "Richtung", french: "la direction", type: "nom", gender: "f" },
  { german: "E-Mail", french: "l’e-mail", type: "nom", gender: "f" },
  { german: "Nachricht", french: "le message", type: "nom", gender: "f" },
  { german: "Korrektur", french: "la correction", type: "nom", gender: "f" },
  { german: "Adresse", french: "l’adresse", type: "nom", gender: "f" },
  { german: "Passwort", french: "le mot de passe", type: "nom", gender: "n" },
  { german: "Teller", french: "l'assiette", type: "nom", gender: "m" },
  { german: "Pfote", french: "la patte", type: "nom", gender: "f" },
  { german: "Farbe", french: "la couleur", type: "nom", gender: "f" },
  { german: "Zahl", french: "le nombre", type: "nom", gender: "f" },
  { german: "Umwelt", french: "l'environnement", type: "nom", gender: "f" },
  { german: "Bereich", french: "le domaine", type: "nom", gender: "m" },
  { german: "Flasche", french: "la bouteille", type: "nom", gender: "f" },
  { german: "Fleisch", french: "la viande", type: "nom", gender: "n" },
  { german: "Mannschaft", french: "l'équipe", type: "nom", gender: "f" },
  { german: "Licht", french: "la lumière", type: "nom", gender: "n" },
  { german: "Schatten", french: "l’ombre", type: "nom", gender: "m" },
  { german: "Markt", french: "le marché", type: "nom", gender: "m" },
  { german: "Wolke", french: "le nuage", type: "nom", gender: "f" },
  { german: "Nächste", french: "le prochain", type: "nom", gender: "m" },
  { german: "Laune", french: "l'humeur", type: "nom", gender: "f" },
  { german: "Körper", french: "le corps", type: "nom", gender: "m" },
  { german: "Gesicht", french: "le visage", type: "nom", gender: "n" },
  { german: "Abend", french: "le soir", type: "nom", gender: "m" },
  { german: "Mittag", french: "le midi", type: "nom", gender: "m" },
  { german: "Kathedrale", french: "la cathédrale", type: "nom", gender: "f" },
  { german: "Haushalt", french: "le budget", type: "nom", gender: "m" },
  { german: "Sorge", french: "le souci", type: "nom", gender: "f" },
  { german: "Pfütze", french: "la flaque d'eau", type: "nom", gender: "f" },
  { german: "Matsch", french: "la boue", type: "nom", gender: "m" },
  { german: "Gänsehaut", french: "la chair de poule", type: "nom", gender: "f" },
  { german: "Verzeihung", french: "pardon", type: "nom", gender: "f" },
  { german: "Urenkel", french: "l'arrière-petit-enfant", type: "nom", gender: "m" },
  { german: "Wetter", french: "la météo", type: "nom", gender: "n" },
  { german: "Wohnzimmer", french: "le salon", type: "nom", gender: "n" },
  { german: "Sofa", french: "le canapé", type: "nom", gender: "n" },
  { german: "Fernsehen", french: "la télévision", type: "nom", gender: "n" },
  { german: "Regen", french: "la pluie", type: "nom", gender: "m" },
  { german: "Blitz", french: "la foudre", type: "nom", gender: "m" },
  { german: "Lade", french: "le tiroir", type: "nom", gender: "f" },
  { german: "Ebene", french: "le niveau", type: "nom", gender: "f" },
  { german: "Folge", french: "une suite", type: "nom", gender: "f" },
  { german: "Funktion", french: "une fonction", type: "nom", gender: "f" },
  { german: "Auge", french: "l’œil", type: "nom", gender: "n" },
  { german: "Ohr", french: "l’oreille", type: "nom", gender: "n" },
  { german: "Mund", french: "la bouche", type: "nom", gender: "m" },
  { german: "Verkehr", french: "le trafic", type: "nom", gender: "m" },
  { german: "TransportLinie", french: "une ligne de transport", type: "nom", gender: "f" },
  { german: "Linie", french: "une ligne", type: "nom", gender: "f" },
  { german: "Pfeil", french: "une flèche", type: "nom", gender: "m" },
  { german: "Krankenwagen", french: "l'ambulance", type: "nom", gender: "m" },
  { german: "Runde", french: "le rond", type: "nom", gender: "f" },
  { german: "Sitz", french: "le siège", type: "nom", gender: "m" },
  { german: "Rechteck", french: "le rectangle", type: "nom", gender: "n" },
  { german: "Quadrat", french: "le carré", type: "nom", gender: "n" },
  { german: "Dreieck", french: "le triangle", type: "nom", gender: "n" },
  { german: "Wörterbuch", french: "le dictionnaire", type: "nom", gender: "n" },
  { german: "Finger", french: "le doigt", type: "nom", gender: "m" },
  { german: "Fuß", french: "le pied", type: "nom", gender: "m" },
  { german: "Herz", french: "le cœur", type: "nom", gender: "n" },
  { german: "Ware", french: "la marchandise", type: "nom", gender: "f" },
  { german: "Medikament", french: "le médicament", type: "nom", gender: "n" },
  { german: "Verbesserung", french: "l'amélioration", type: "nom", gender: "f" },
  { german: "Denkmal", french: "le monument", type: "nom", gender: "n" },
  { german: "Grenze", french: "la limite / la frontière", type: "nom", gender: "f" },
  { german: "Moment", french: "le moment", type: "nom", gender: "m" },
  { german: "Schlüssel", french: "la clé", type: "nom", gender: "m" },
  { german: "Schmerz", french: "la douleur", type: "nom", gender: "m" },
  { german: "Mal", french: "la fois", type: "nom", gender: "n" },
  { german: "Schutz", french: "la protection", type: "nom", gender: "m" },
  { german: "Zentrum", french: "le centre", type: "nom", gender: "n" },
  { german: "Gasse", french: "la ruelle", type: "nom", gender: "f" },
  { german: "Reichtum", french: "la richesse", type: "nom", gender: "m" },
  { german: "Terrasse", french: "la terrasse", type: "nom", gender: "f" },
  { german: "Veranstaltung", french: "l'événement", type: "nom", gender: "f" },
  { german: "Rot", french: "le rouge", type: "nom", gender: "n" },
  { german: "Blau", french: "le bleu", type: "nom", gender: "n" },
  { german: "Grün", french: "le vert", type: "nom", gender: "n" },
  { german: "Büro", french: "le bureau", type: "nom", gender: "n" },
  { german: "Klient", french: "le client", type: "nom", gender: "m" },
  { german: "Link", french: "le lien", type: "nom", gender: "m" },
  { german: "Beistandschaft", french: "la curatelle", type: "nom", gender: "f" },
  { german: "Vorhang", french: "le rideau", type: "nom", gender: "m" },
  { german: "Gelb", french: "le jaune", type: "nom", gender: "n" },
  { german: "Orange", french: "l’orange (couleur)", type: "nom", gender: "n" },
  { german: "Rosa", french: "le rose", type: "nom", gender: "n" },
  { german: "Lila", french: "le violet", type: "nom", gender: "n" },
  { german: "Violett", french: "le violet", type: "nom", gender: "n" },
  { german: "Braun", french: "le marron", type: "nom", gender: "n" },
  { german: "Schwarz", french: "le noir", type: "nom", gender: "n" },
  { german: "Weiß", french: "le blanc", type: "nom", gender: "n" },
  { german: "Grau", french: "le gris", type: "nom", gender: "n" },
  { german: "Stau", french: "l'embouteillage", type: "nom", gender: "m" },
  { german: "Beige", french: "le beige", type: "nom", gender: "n" },
  { german: "Türkis", french: "le turquoise", type: "nom", gender: "n" },
  { german: "Angebot", french: "l'offre", type: "nom", gender: "n" },
  { german: "Anwalt", french: "l'avocat", type: "nom", gender: "m" },

  // Verbes (verbe)
  { german: "sein", french: "être", type: "verbe" },
  { german: "haben", french: "avoir", type: "verbe" },
  { german: "werden", french: "devenir", type: "verbe" },
  { german: "können", french: "pouvoir (capacité)", type: "verbe" },
  { german: "müssen", french: "devoir (obligation)", type: "verbe" },
  { german: "wollen", french: "vouloir", type: "verbe" },
  { german: "sollen", french: "devoir (conseil)", type: "verbe" },
  { german: "mögen", french: "aimer (bien)", type: "verbe" },
  { german: "machen", french: "faire", type: "verbe" },
  { german: "tun", french: "faire (familier)", type: "verbe" },
  { german: "gehen", french: "aller", type: "verbe" },
  { german: "kommen", french: "venir", type: "verbe" },
  { german: "sehen", french: "voir", type: "verbe" },
  { german: "kopieren", french: "copier", type: "verbe" },
  { german: "kleben", french: "coller", type: "verbe" },
  { german: "erkennen", french: "détecter", type: "verbe" },
  { german: "beraten", french: "conseiller", type: "verbe" },
  { german: "sich rühmen", french: "se vanter", type: "verbe" },
  { german: "hören", french: "entendre", type: "verbe" },
  { german: "sagen", french: "dire", type: "verbe" },
  { german: "sprechen", french: "parler", type: "verbe" },
  { german: "fragen", french: "demander", type: "verbe" },
  { german: "antworten", french: "répondre", type: "verbe" },
  { german: "wissen", french: "savoir", type: "verbe" },
  { german: "kennen", french: "connaître", type: "verbe" },
  { german: "denken", french: "penser", type: "verbe" },
  { german: "stehen", french: "être debout / se tenir", type: "verbe" },
  { german: "glauben", french: "croire", type: "verbe" },
  { german: "leben", french: "vivre", type: "verbe" },
  { german: "lieben", french: "aimer (sentiment)", type: "verbe" },
  { german: "essen", french: "manger", type: "verbe" },
  { german: "trinken", french: "boire", type: "verbe" },
  { german: "schlafen", french: "dormir", type: "verbe" },
  { german: "arbeiten", french: "travailler", type: "verbe" },
  { german: "lernen", french: "apprendre", type: "verbe" },
  { german: "studieren", french: "étudier", type: "verbe" },
  { german: "fahren", french: "conduire / aller", type: "verbe" },
  { german: "laufen", french: "courir / marcher", type: "verbe" },
  { german: "bleiben", french: "rester", type: "verbe" },
  { german: "beschleunigen", french: "accélérer", type: "verbe" },
  { german: "beginnen", french: "commencer", type: "verbe" },
  { german: "enden", french: "finir", type: "verbe" },
  { german: "kaufen", french: "acheter", type: "verbe" },
  { german: "verkaufen", french: "vendre", type: "verbe" },
  { german: "bereit sein", french: "être prêt", type: "verbe" },
  { german: "brauchen", french: "avoir besoin de", type: "verbe" },
  { german: "fördern", french: "promouvoir", type: "verbe" },
  { german: "suchen", french: "chercher", type: "verbe" },
  { german: "finden", french: "trouver", type: "verbe" },
  { german: "geben", french: "donner", type: "verbe" },
  { german: "nehmen", french: "prendre", type: "verbe" },
  { german: "speichern", french: "enregistrer", type: "verbe" },
  { german: "helfen", french: "aider", type: "verbe" },
  { german: "zeigen", french: "montrer", type: "verbe" },
  { german: "sitzen", french: "être assis", type: "verbe" },
  { german: "schnarchen", french: "ronfler", type: "verbe" },
  { german: "liegen", french: "être couché / se trouver", type: "verbe" },
  { german: "stellen", french: "poser (debout)", type: "verbe" },
  { german: "legen", french: "poser (couché)", type: "verbe" },
  { german: "setzen", french: "asseoir", type: "verbe" },
  { german: "servieren", french: "servir", type: "verbe" },
  { german: "tragen", french: "porter", type: "verbe" },
  { german: "ziehen", french: "tirer", type: "verbe" },
  { german: "weiterverkaufen", french: "revendre", type: "verbe" },
  { german: "einziehen", french: "emménager", type: "verbe" },
  { german: "ausschalten", french: "désactiver", type: "verbe" },
  { german: "sich entfernen", french: "s'enlever", type: "verbe" },
  { german: "fehlen", french: "manquer", type: "verbe" },
  { german: "flüstern", french: "chuchoter", type: "verbe" },
  { german: "ermöglichen", french: "permettre", type: "verbe" },
  { german: "drücken", french: "pousser / appuyer", type: "verbe" },
  { german: "werfen", french: "jeter", type: "verbe" },
  { german: "fallen", french: "tomber", type: "verbe" },
  { german: "steigen", french: "monter", type: "verbe" },
  { german: "gründen", french: "fonder", type: "verbe" },
  { german: "sinken", french: "descendre / couler", type: "verbe" },
  { german: "bauen", french: "construire", type: "verbe" },
  { german: "zerstören", french: "détruire", type: "verbe" },
  { german: "öffnen", french: "ouvrir", type: "verbe" },
  { german: "korrigieren", french: "corriger", type: "verbe" },
  { german: "schließen", french: "fermer", type: "verbe" },
  { german: "vergessen", french: "oublier", type: "verbe" },
  { german: "erinnern", french: "se souvenir", type: "verbe" },
  { german: "bestellen", french: "commander", type: "verbe" },
  { german: "wünschen", french: "souhaiter", type: "verbe" },
  { german: "erfüllen", french: "exaucer", type: "verbe" },
  { german: "eingeben", french: "entrer", type: "verbe" },
  { german: "ausgehen", french: "sortir", type: "verbe" },
  { german: "erzählen", french: "raconter", type: "verbe" },
  { german: "erklären", french: "expliquer", type: "verbe" },
  { german: "sich wundern über", french: "s'étonner de", type: "verbe" },
  { german: "überprüfen", french: "vérifier", type: "verbe" },
  { german: "benutzen", french: "utiliser", type: "verbe" },
  { german: "bedeuten", french: "signifier", type: "verbe" },
  { german: "gewinnen", french: "gagner", type: "verbe" },
  { german: "verlieren", french: "perdre", type: "verbe" },
  { german: "bieten", french: "offrir", type: "verbe" },
  { german: "demonstrieren", french: "démontrer", type: "verbe" },
  { german: "berechnen", french: "calculer", type: "verbe" },
  { german: "jammern", french: "se plaindre", type: "verbe" },
  { german: "weiterleiten", french: "transmettre", type: "verbe" },
  { german: "senden", french: "envoyer", type: "verbe" },
  { german: "funktionieren", french: "fonctionner", type: "verbe" },
  { german: "verbessern", french: "améliorer", type: "verbe" },
  { german: "ersetzen", french: "remplacer", type: "verbe" },
  { german: "leisten", french: "fournir", type: "verbe" },
  { german: "sparen", french: "économiser", type: "verbe" },
  { german: "präsentieren", french: "présenter", type: "verbe" },
  { german: "sich vorstellen", french: "se présenter", type: "verbe" },
  { german: "benennen", french: "nommer", type: "verbe" },
  { german: "reisen", french: "voyager", type: "verbe" },
  { german: "nachdenken", french: "réfléchir", type: "verbe" },
  { german: "anhören", french: "écouter", type: "verbe" },
  { german: "merken", french: "retenir", type: "verbe" },
  { german: "errichten", french: "ériger", type: "verbe" },
  { german: "platzieren", french: "placer", type: "verbe" },
  { german: "bemerken", french: "remarquer", type: "verbe" },
  { german: "markieren", french: "marquer", type: "verbe" },
  { german: "übernehmen", french: "reprendre / remplacer", type: "verbe" },
  { german: "besuchen", french: "visiter / rendre visite", type: "verbe" },
  { german: "anrufen", french: "appeler (au téléphone)", type: "verbe" },
  { german: "schreiben", french: "écrire", type: "verbe" },
  { german: "bekommen", french: "obtenir", type: "verbe" },
  { german: "schneiden", french: "couper", type: "verbe" },
  { german: "abdecken", french: "couvrir", type: "verbe" },
  { german: "lesen", french: "lire", type: "verbe" },
  { german: "zeichnen", french: "dessiner", type: "verbe" },
  { german: "fotografieren", french: "photographier", type: "verbe" },
  { german: "übersetzen", french: "traduire", type: "verbe" },
  { german: "kochen", french: "cuisiner", type: "verbe" },
  { german: "backen", french: "cuire au four", type: "verbe" },
  { german: "fortsetzen", french: "continuer", type: "verbe" },
  { german: "waschen", french: "laver", type: "verbe" },
  { german: "putzen", french: "nettoyer", type: "verbe" },
  { german: "springen", french: "sauter", type: "verbe" },
  { german: "tanzen", french: "danser", type: "verbe" },
  { german: "schauen", french: "regarder", type: "verbe" },
  { german: "sich fragen", french: "se poser la question", type: "verbe" },
  { german: "singen", french: "chanter", type: "verbe" },
  { german: "lassen", french: "laisser", type: "verbe" },
  { german: "buchstabieren", french: "épeler", type: "verbe" },
  { german: "wiederholen", french: "répéter", type: "verbe" },
  { german: "verstehen", french: "comprendre", type: "verbe" },
  { german: "sich positionieren", french: "se positionner", type: "verbe" },
  { german: "formulieren", french: "former", type: "verbe" },
  { german: "färben", french: "teindre", type: "verbe" },
  { german: "beißen", french: "mordre", type: "verbe" },
  { german: "schlagen", french: "battre", type: "verbe" },
  { german: "üben", french: "s'entraîner", type: "verbe" },
  { german: "kämpfen", french: "se battre", type: "verbe" },
  { german: "treffen", french: "rencontrer", type: "verbe" },
  { german: "versuchen", french: "essayer", type: "verbe" },
  { german: "dauern", french: "durer", type: "verbe" },
  { german: "erreichen", french: "atteindre", type: "verbe" },
  { german: "verlassen", french: "quitter", type: "verbe" },
  { german: "sich freuen", french: "se réjouir", type: "verbe" },
  { german: "sich interessieren", french: "s’intéresser", type: "verbe" },
  { german: "sich erinnern", french: "se souvenir", type: "verbe" },
  { german: "sich beeilen", french: "se dépêcher", type: "verbe" },
  { german: "sich waschen", french: "se laver", type: "verbe" },
  { german: "sich anziehen", french: "s’habiller", type: "verbe" },
  { german: "sich ausziehen", french: "se déshabiller", type: "verbe" },
  { german: "sich setzen", french: "s’asseoir", type: "verbe" },
  { german: "sich fühlen", french: "se sentir", type: "verbe" },
  { german: "wandern", french: "faire de la randonnée", type: "verbe" },
  { german: "kleiden", french: "habiller", type: "verbe" },
  { german: "wenden", french: "retourner", type: "verbe" },
  { german: "entkleiden", french: "se déshabiller", type: "verbe" },
  { german: "bringen", french: "apporter", type: "verbe" },
  { german: "klettern", french: "escalader", type: "verbe" },
  { german: "schwimmen", french: "nager", type: "verbe" },
  { german: "folgen", french: "suivre", type: "verbe" },
  { german: "tauchen", french: "plonger", type: "verbe" },
  { german: "verschieben", french: "déplacer ou reporter", type: "verbe" },
  { german: "ergänzen", french: "compléter", type: "verbe" },
  { german: "fliegen", french: "voler (en avion)", type: "verbe" },
  { german: "bekennen", french: "avouer", type: "verbe" },
  { german: "begleiten", french: "accompagner", type: "verbe" },
  { german: "landen", french: "atterrir", type: "verbe" },
  { german: "abfahren", french: "partir (véhicule)", type: "verbe" },
  { german: "ankommen", french: "arriver", type: "verbe" },
  { german: "aufhören", french: "arrêter", type: "verbe" },
  { german: "herunterladen", french: "télécharger", type: "verbe" },
  { german: "laden", french: "charger", type: "verbe" },
  { german: "klicken", french: "cliquer", type: "verbe" },
  { german: "erhalten", french: "recevoir", type: "verbe" },
  { german: "befragen", french: "interroger", type: "verbe" },
  { german: "prägen", french: "rythmer", type: "verbe" },
  { german: "verlaufen", french: "se perdre", type: "verbe" },
  { german: "mieten", french: "louer", type: "verbe" },
  { german: "bezahlen", french: "payer", type: "verbe" },
  { german: "zahlen", french: "compter", type: "verbe" },
  { german: "kosten", french: "coûter", type: "verbe" },
  { german: "besichtigen", french: "visiter (lieu)", type: "verbe" },
  { german: "bewundern", french: "admirer", type: "verbe" },
  { german: "genießen", french: "profiter / savourer", type: "verbe" },
  { german: "fühlen", french: "ressentir", type: "verbe" },
  { german: "riechen", french: "sentir (odorat)", type: "verbe" },
  { german: "schmecken", french: "goûter", type: "verbe" },
  { german: "anfassen", french: "toucher", type: "verbe" },
  { german: "heilen", french: "guérir", type: "verbe" },
  { german: "entdecken", french: "découvrir", type: "verbe" },
  { german: "zustimmen", french: "être d'accord", type: "verbe" },
  { german: "besitzen", french: "posséder", type: "verbe" },
  { german: "vorbereiten", french: "préparer", type: "verbe" },
  { german: "einladen", french: "inviter", type: "verbe" },
  { german: "reparieren", french: "réparer", type: "verbe" },
  { german: "wählen", french: "choisir / composer", type: "verbe" },
  { german: "warten", french: "attendre", type: "verbe" },
  { german: "ändern", french: "changer", type: "verbe" },
  { german: "erstellen", french: "créer", type: "verbe" },
  { german: "behalten", french: "garder", type: "verbe" },
  { german: "teilen", french: "partager", type: "verbe" },

  // Adjectifs (adjectif)
  { german: "gut", french: "bon", type: "adjectif" },
  { german: "historisch", french: "historique", type: "adjectif" },
  { german: "wunderschön", french: "magnifique", type: "adjectif" },
  { german: "unglaublich", french: "incroyable", type: "adjectif" },
  { german: "glaublich", french: "croyable", type: "adjectif" },
  { german: "schlecht", french: "mauvais", type: "adjectif" },
  { german: "bekannt", french: "connu", type: "adjectif" },
  { german: "überlegt", french: "réfléchi", type: "adjectif" },
  { german: "unbekannt", french: "inconnu", type: "adjectif" },
  { german: "groß", french: "grand", type: "adjectif" },
  { german: "klein", french: "petit", type: "adjectif" },
  { german: "schön", french: "beau", type: "adjectif" },
  { german: "hübsch", french: "joli", type: "adjectif" },
  { german: "ordentlich", french: "ordonné", type: "adjectif" },
  { german: "hässlich", french: "laid", type: "adjectif" },
  { german: "alt", french: "vieux", type: "adjectif" },
  { german: "jung", french: "jeune", type: "adjectif" },
  { german: "ehrgeizig", french: "ambitieux", type: "adjectif" },
  { german: "verständlich", french: "compréhensible", type: "adjectif" },
  { german: "neu", french: "neuf", type: "adjectif" },
  { german: "altmodisch", french: "démodé", type: "adjectif" },
  { german: "anwesend", french: "présent", type: "adjectif" },
  { german: "abwesend", french: "absent", type: "adjectif" },
  { german: "null", french: "nul", type: "adjectif" },
  { german: "freundlich", french: "amical", type: "adjectif" },
  { german: "nett", french: "gentil", type: "adjectif" },
  { german: "traurig", french: "triste", type: "adjectif" },
  { german: "glücklich", french: "heureux", type: "adjectif" },
  { german: "müde", french: "fatigué", type: "adjectif" },
  { german: "hungrig", french: "affamé", type: "adjectif" },
  { german: "fertig", french: "prêt", type: "adjectif" },
  { german: "durstig", french: "assoiffé", type: "adjectif" },
  { german: "nützlich", french: "utile", type: "adjectif" },
  { german: "super", french: "superbe", type: "adjectif" },
  { german: "veränderbar", french: "modifiable", type: "adjectif" },
  { german: "pünktlich", french: "ponctuel", type: "adjectif" },
  { german: "vorsichtig", french: "prudent", type: "adjectif" },
  { german: "lustig", french: "drôle", type: "adjectif" },
  { german: "teuer", french: "cher", type: "adjectif" },
  { german: "ernst", french: "sérieux", type: "adjectif" },
  { german: "billig", french: "bon marché", type: "adjectif" },
  { german: "wichtig", french: "important", type: "adjectif" },
  { german: "wirklich", french: "vraiment", type: "adjectif" },
  { german: "erhellter", french: "illuminé", type: "adjectif" },
  { german: "einfach", french: "simple", type: "adjectif" },
  { german: "schwierig", french: "difficile", type: "adjectif" },
  { german: "unbegrenzt", french: "illimité", type: "adjectif" },
  { german: "verschieden", french: "différent", type: "adjectif" },
  { german: "einzigartig", french: "unique", type: "adjectif" },
  { german: "politisch", french: "politique", type: "adjectif" },
  { german: "zusammen", french: "ensemble", type: "adjectif" },
  { german: "wirtschaftlich", french: "économique", type: "adjectif" },
  { german: "belebt", french: "animée", type: "adjectif" },
  { german: "schnell", french: "rapide", type: "adjectif" },
  { german: "langsam", french: "lent", type: "adjectif" },
  { german: "stark", french: "fort", type: "adjectif" },
  { german: "schwach", french: "faible", type: "adjectif" },
  { german: "hell", french: "clair", type: "adjectif" },
  { german: "dunkel", french: "sombre", type: "adjectif" },
  { german: "warm", french: "chaud", type: "adjectif" },
  { german: "kalt", french: "froid", type: "adjectif" },
  { german: "trocken", french: "sec", type: "adjectif" },
  { german: "nass", french: "mouillé", type: "adjectif" },
  { german: "möglich", french: "possible", type: "adjectif" },
  { german: "verfügbar", french: "disponible", type: "adjectif" },
  { german: "sauber", french: "propre", type: "adjectif" },
  { german: "schmutzig", french: "sale", type: "adjectif" },
  { german: "hart", french: "dur", type: "adjectif" },
  { german: "weich", french: "mou", type: "adjectif" },
  { german: "scharf", french: "tranchant / épicé", type: "adjectif" },
  { german: "stumpf", french: "émoussé", type: "adjectif" },
  { german: "lokal", french: "local", type: "adjectif" },
  { german: "geduldig", french: "patient", type: "adjectif" },
  { german: "ungeduldig", french: "impatient", type: "adjectif" },
  { german: "laut", french: "bruyant", type: "adjectif" },
  { german: "leise", french: "silencieux", type: "adjectif" },
  { german: "nötig", french: "nécessaire", type: "adjectif" },
  { german: "nah", french: "proche", type: "adjectif" },
  { german: "fern", french: "lointain", type: "adjectif" },
  { german: "leer", french: "vide", type: "adjectif" },
  { german: "voll", french: "plein", type: "adjectif" },
  { german: "gemeinsam", french: "commun", type: "adjectif" },
  { german: "offen", french: "ouvert", type: "adjectif" },
  { german: "geschlossen", french: "fermé", type: "adjectif" },
  { german: "malerisch", french: "pittoresque", type: "adjectif" },
  { german: "reich", french: "riche", type: "adjectif" },
  { german: "arm", french: "pauvre", type: "adjectif" },
  { german: "gesund", french: "en bonne santé", type: "adjectif" },
  { german: "anstrengend", french: "épuisant", type: "adjectif" },
  { german: "krank", french: "malade", type: "adjectif" },
  { german: "original", french: "original", type: "adjectif" },
  { german: "froh", french: "content", type: "adjectif" },
  { german: "atemberaubend", french: "époustouflant", type: "adjectif" },
  { german: "entdeckend", french: "couvrant", type: "adjectif" },
  { german: "klug", french: "intelligent", type: "adjectif" },
  { german: "dumm", french: "stupide", type: "adjectif" },
  { german: "ruhig", french: "calme", type: "adjectif" },
  { german: "glänzend", french: "brillant", type: "adjectif" },
  { german: "farbig", french: "coloré", type: "adjectif" },
  { german: "wenig", french: "peu", type: "adjectif" },
  { german: "interessant", french: "intéressant", type: "adjectif" },
  { german: "langweilig", french: "ennuyeux", type: "adjectif" },
  { german: "glatt", french: "lisse", type: "adjectif" },
  { german: "fett", french: "gros", type: "adjectif" },
  { german: "schlank", french: "maigre", type: "adjectif" },
  { german: "rau", french: "rugueux", type: "adjectif" },
  { german: "heiß", french: "très chaud / brûlant", type: "adjectif" },
  { german: "kühl", french: "frais", type: "adjectif" },
  { german: "duldsam", french: "tolérant", type: "adjectif" },
  { german: "unduldsam", french: "intolérant", type: "adjectif" },
  { german: "mutig", french: "courageux", type: "adjectif" },
  { german: "ängstlich", french: "peureux", type: "adjectif" },
  { german: "beeindruckend", french: "impressionnant", type: "adjectif" },
  { german: "gefährlich", french: "dangereux", type: "adjectif" },
  { german: "sicher", french: "sûr / en sécurité", type: "adjectif" },
  { german: "ganz", french: "entier", type: "adjectif" },
  { german: "bequem", french: "confortable", type: "adjectif" },
  { german: "unbequem", french: "inconfortable", type: "adjectif" },
  { german: "köstlich", french: "délicieux", type: "adjectif" },
  { german: "spannend", french: "captivant", type: "adjectif" },
  { german: "wild", french: "sauvage", type: "adjectif" },
  { german: "tief", french: "profond", type: "adjectif" },
  { german: "flach", french: "plat", type: "adjectif" },
  { german: "richtig", french: "vrai", type: "adjectif" },
  { german: "falsch", french: "faux", type: "adjectif" },
  { german: "kurz", french: "court", type: "adjectif" },
  { german: "lang", french: "long", type: "adjectif" },
  { german: "frei", french: "libre", type: "adjectif" },
  { german: "besetzt", french: "occupé", type: "adjectif" },
  { german: "genau", french: "exactement", type: "adjectif" },

  // Adverbes (adverbe)
  { german: "ja", french: "oui", type: "adverbe" },
  { german: "nein", french: "non", type: "adverbe" },
  { german: "heute", french: "aujourd’hui", type: "adverbe" },
  { german: "gestern", french: "hier", type: "adverbe" },
  { german: "morgen", french: "demain", type: "adverbe" },
  { german: "jetzt", french: "maintenant", type: "adverbe" },
  { german: "bald", french: "bientôt", type: "adverbe" },
  { german: "schon", french: "déjà", type: "adverbe" },
  { german: "noch", french: "encore", type: "adverbe" },
  { german: "nie", french: "jamais", type: "adverbe" },
  { german: "immer", french: "toujours", type: "adverbe" },
  { german: "manchmal", french: "parfois", type: "adverbe" },
  { german: "oft", french: "souvent", type: "adverbe" },
  { german: "selten", french: "rarement", type: "adverbe" },
  { german: "dort", french: "là-bas", type: "adverbe" },
  { german: "netz", french: "juste", type: "adverbe" },
  { german: "da", french: "là", type: "adverbe" },
  { german: "hier", french: "ici", type: "adverbe" },
  { german: "natürlich", french: "bien sûr", type: "adverbe" },
  { german: "ernstlich", french: "sérieusement", type: "adverbe" },
  { german: "überall", french: "partout", type: "adverbe" },
  { german: "nirgendwo", french: "nulle part", type: "adverbe" },
  { german: "schnell", french: "rapidement", type: "adverbe" },
  { german: "langsam", french: "lentement", type: "adverbe" },
  { german: "gern", french: "volontiers", type: "adverbe" },
  { german: "vielleicht", french: "peut-être", type: "adverbe" },
  { german: "bestimmt", french: "certainement", type: "adverbe" },
  { german: "draußen", french: "dehors", type: "adverbe" },
  { german: "drinnen", french: "à l’intérieur", type: "adverbe" },
  { german: "oben", french: "en haut", type: "adverbe" },
  { german: "unten", french: "en bas", type: "adverbe" },
  { german: "vorne", french: "devant", type: "adverbe" },
  { german: "zu", french: "vers", type: "adverbe" },
  { german: "hinten", french: "derrière", type: "adverbe" },
  { german: "sofort", french: "immédiatement", type: "adverbe" },
  { german: "gerade", french: "tout de suite / actuellement", type: "adverbe" },
  { german: "plötzlich", french: "soudain", type: "adverbe" },
  { german: "genug", french: "assez", type: "adverbe" },
  { german: "leise", french: "doucement (son)", type: "adverbe" },
  { german: "laut", french: "bruyamment", type: "adverbe" },
  { german: "täglich", french: "quotidiennement", type: "adverbe" },
  { german: "oftmals", french: "fréquemment", type: "adverbe" },
  { german: "zufällig", french: "par hasard", type: "adverbe" },
  { german: "wahrscheinlich", french: "probablement", type: "adverbe" },
  { german: "schließlich", french: "finalement", type: "adverbe" },
  { german: "leider", french: "malheureusement", type: "adverbe" },
  { german: "glücklicherweise", french: "heureusement", type: "adverbe" },
  { german: "sogar", french: "même", type: "adverbe" },
  { german: "also", french: "donc", type: "adverbe" },
  { german: "dann", french: "alors / ensuite", type: "adverbe" },
  { german: "sonst", french: "sinon", type: "adverbe" },
  { german: "ab", french: "dès", type: "adverbe" },
  { german: "dennoch", french: "pourtant", type: "adverbe" },
  { german: "auch", french: "aussi", type: "adverbe" },
  { german: "als", french: "que (comparatif)", type: "adverbe" },
  { german: "oder", french: "or", type: "adverbe" },
  { german: "vor", french: "avant", type: "adverbe" },
  { german: "nach", french: "après", type: "adverbe" },
  { german: "jedoch", french: "cependant", type: "adverbe" },
  { german: "während", french: "pendant", type: "adverbe" },
  { german: "darüber", french: "à ce sujet", type: "adverbe" },
  { german: "hierzu", french: "avec ceci", type: "adverbe" },
  { german: "hierzu bereit", french: "à faire ceci", type: "adverbe" },
  { german: "nur", french: "seulement", type: "adverbe" },
  { german: "hinaus", french: "en outre", type: "adverbe" },
  { german: "zuletzt", french: "dernièrement", type: "adverbe" },
  { german: "andere", french: "autre", type: "adverbe" },
  { german: "wegen", french: "à cause de", type: "adverbe" },
  { german: "zwischen", french: "entre", type: "adverbe" },
  { german: "mehrfach", french: "plusieurs", type: "adverbe" },
  { german: "niemand", french: "personne", type: "adverbe" },
  { german: "mehr", french: "plus", type: "adverbe" },
  { german: "weniger", french: "moins", type: "adverbe" },
  { german: "hinterher", french: "à la suite de", type: "adverbe" },
  { german: "neben", french: "à côté", type: "adverbe" },
  { german: "jede", french: "chaque", type: "adverbe" },
  { german: "irgendetwas", french: "quelque chose", type: "adverbe" },
  { german: "vollständig", french: "entièrement", type: "adverbe" },
  { german: "wie", french: "comme", type: "adverbe" },
  { german: "bis", french: "jusqu'à", type: "adverbe" },
  { german: "herzlichen", french: "cordialement", type: "adverbe" },
  { german: "außerhalb", french: "en dehors de", type: "adverbe" },
  { german: "dabei", french: "avec lui / y", type: "adverbe" },
  { german: "innerhalb", french: "à l'intérieur de", type: "adverbe" },
  { german: "Oberteil", french: "dessus", type: "adverbe" },
  { german: "durch", french: "à travers", type: "adverbe" },
  { german: "Unterseite", french: "dessous", type: "adverbe" },
  { german: "bei", french: "chez", type: "adverbe" },
  { german: "paar", french: "quelque", type: "adverbe" },
  { german: "gegeneinander", french: "les uns contre les autres", type: "adverbe" },
  { german: "füreinander", french: "l'un pour l'autre", type: "adverbe" },
  { german: "miteinander", french: "les uns avec les autres", type: "adverbe" },
  { german: "voneinander", french: "l'un de l'autre", type: "adverbe" },
  { german: "einander", french: "l'un l'autre", type: "adverbe" },
  { german: "lieber", french: "(mon) cher / plutôt", type: "adverbe" },
  { german: "gleich", french: "également / tout de suite", type: "adverbe" },
  { german: "früher", french: "auparavant", type: "adverbe" },

  // Mots clés (mot clé)
  { german: "bitte", french: "s’il vous plaît", type: "mot clé" },
  { german: "danke", french: "merci", type: "mot clé" },
  { german: "hallo", french: "bonjour", type: "mot clé" },
  { german: "tschüss", french: "au revoir", type: "mot clé" },

  // Pronoms (pronom)
  { german: "ich", french: "je", type: "pronom" },
  { german: "du", french: "tu", type: "pronom" },
  { german: "er", french: "il", type: "pronom" },
  { german: "sie", french: "elle / ils / elles", type: "pronom" },
  { german: "es", french: "ça / il (neutre)", type: "pronom" },
  { german: "wir", french: "nous", type: "pronom" },
  { german: "ihr", french: "vous (pluriel)", type: "pronom" },
  { german: "Sie", french: "vous (politesse)", type: "pronom" },

  // Conjonctions (conjonc)
  { german: "und", french: "et", type: "conjonc" },
  { german: "oder", french: "ou", type: "conjonc" },
  { german: "aber", french: "mais", type: "conjonc" },
  { german: "circa", french: "environ", type: "conjonc" },
  { german: "weil", french: "parce que", type: "conjonc" },
  { german: "dass", french: "que", type: "conjonc" },
  { german: "wenn", french: "quand / si", type: "conjonc" },

  // Particules / Autres
  { german: "doch", french: "particule (si)", type: "particule" },
  { german: "sei", french: "soit", type: "autre" },
  { german: "so", french: "si / comme cela", type: "autre" },
  { german: "anstatt", french: "au lieu de", type: "preposition" },

  // Mots interrogatifs (adv/int)
  { german: "wo", french: "où", type: "adv/int" },
  { german: "wann", french: "quand", type: "adv/int" },
  { german: "warum", french: "pourquoi", type: "adv/int" },
  { german: "wie", french: "comment", type: "adv/int" },
  { german: "was", french: "quoi", type: "adv/int" },
  { german: "wer", french: "qui", type: "adv/int" },
  { german: "wohin", french: "vers où", type: "adv/int" },
  { german: "welche Zeit", french: "quelle heure", type: "adv/int" },
  { german: "wieviel", french: "combien", type: "adv/int" }
];