// verben.js

const VERBS = [
  { infinitive: "anfangen", praesens: "er fängt an", praeteritum: "er fing an", perfekt: "er hat angefangen", translation: "commencer" },
  { infinitive: "anhalten", praesens: "er hält an", praeteritum: "er hielt an", perfekt: "er hat angehalten", translation: "s’arrêter" },
  { infinitive: "anziehen", praesens: "er zieht an", praeteritum: "er zog an", perfekt: "er hat angezogen", translation: "mettre (un habit)" },
  { infinitive: "auffallen", praesens: "es fällt auf", praeteritum: "es fiel auf", perfekt: "es ist aufgefallen", translation: "être frappant" },
  { infinitive: "aufstehen", praesens: "er steht auf", praeteritum: "er stand auf", perfekt: "er ist aufgestanden", translation: "se lever" },
  { infinitive: "ausleihen", praesens: "er leiht aus", praeteritum: "er lieh aus", perfekt: "er hat ausgeliehen", translation: "prêter" },
  { infinitive: "aussehen", praesens: "er sieht aus", praeteritum: "er sah aus", perfekt: "er hat ausgesehen", translation: "avoir l’air" },
  { infinitive: "backen", praesens: "er bäckt", praeteritum: "er backte/buk", perfekt: "er hat gebacken", translation: "faire cuire" },
  { infinitive: "befehlen", praesens: "er befiehlt", praeteritum: "er befahl", perfekt: "er hat befohlen", translation: "ordonner" },
  { infinitive: "beginnen", praesens: "er beginnt", praeteritum: "er begann", perfekt: "er hat begonnen", translation: "commencer" },
  { infinitive: "beißen", praesens: "er beißt", praeteritum: "er biss", perfekt: "er hat gebissen", translation: "mordre" },
  { infinitive: "bekommen", praesens: "er bekommt", praeteritum: "er bekam", perfekt: "er hat bekommen", translation: "recevoir" },
  { infinitive: "bergen", praesens: "er birgt", praeteritum: "er barg", perfekt: "er hat geborgen", translation: "sauver, cacher" },
  { infinitive: "betrügen", praesens: "er betrügt", praeteritum: "er betrog", perfekt: "er hat betrogen", translation: "tricher" },
  { infinitive: "biegen", praesens: "er biegt", praeteritum: "er bog", perfekt: "er hat gebogen", translation: "courber, plier" },
  { infinitive: "bieten", praesens: "er bietet", praeteritum: "er bot", perfekt: "er hat geboten", translation: "offrir, proposer" },
  { infinitive: "binden", praesens: "er bindet", praeteritum: "er band", perfekt: "er hat gebunden", translation: "lier, attacher" },
  { infinitive: "bitten", praesens: "er bittet", praeteritum: "er bat", perfekt: "er hat gebeten", translation: "prier, demander" },
  { infinitive: "blasen", praesens: "er bläst", praeteritum: "er blies", perfekt: "er hat geblasen", translation: "souffler" },
  { infinitive: "bleiben", praesens: "er bleibt", praeteritum: "er blieb", perfekt: "er ist geblieben", translation: "rester" },
  { infinitive: "braten", praesens: "er brät", praeteritum: "er briet", perfekt: "er hat gebraten", translation: "cuire, griller" },
  { infinitive: "brechen", praesens: "er bricht", praeteritum: "er brach", perfekt: "er hat gebrochen", translation: "casser, briser" },
  { infinitive: "denken", praesens: "er denkt", praeteritum: "er dachte", perfekt: "er hat gedacht", translation: "penser" },
  { infinitive: "einladen", praesens: "er lädt ein", praeteritum: "er lud ein", perfekt: "er hat eingeladen", translation: "inviter" },
  { infinitive: "einsteigen", praesens: "er steigt ein", praeteritum: "er stieg ein", perfekt: "er ist eingestiegen", translation: "monter (véhicule)" },
  { infinitive: "empfangen", praesens: "er empfängt", praeteritum: "er empfing", perfekt: "er hat empfangen", translation: "recevoir, accueillir" },
  { infinitive: "empfehlen", praesens: "er empfiehlt", praeteritum: "er empfahl", perfekt: "er hat empfohlen", translation: "recommander" },
  { infinitive: "empfinden", praesens: "er empfindet", praeteritum: "er empfand", perfekt: "er hat empfunden", translation: "ressentir" },
  { infinitive: "erschrecken", praesens: "er erschrickt", praeteritum: "er erschrak", perfekt: "er ist erschrocken", translation: "prendre peur" },
  { infinitive: "essen", praesens: "er isst", praeteritum: "er aß", perfekt: "er hat gegessen", translation: "manger" },
  { infinitive: "fahren", praesens: "er fährt", praeteritum: "er fuhr", perfekt: "er ist gefahren", translation: "aller (en véhicule)" },
  { infinitive: "fallen", praesens: "er fällt", praeteritum: "er fiel", perfekt: "er ist gefallen", translation: "tomber" },
  { infinitive: "fangen", praesens: "er fängt", praeteritum: "er fing", perfekt: "er hat gefangen", translation: "attraper" },
  { infinitive: "finden", praesens: "er findet", praeteritum: "er fand", perfekt: "er hat gefunden", translation: "trouver" },
  { infinitive: "fliegen", praesens: "er fliegt", praeteritum: "er flog", perfekt: "er ist geflogen", translation: "voler" },
  { infinitive: "fliehen", praesens: "er flieht", praeteritum: "er floh", perfekt: "er ist geflohen", translation: "s’enfuir" },
  { infinitive: "fließen", praesens: "er fließt", praeteritum: "er floss", perfekt: "er ist geflossen", translation: "couler, s’écouler" },
  { infinitive: "fressen", praesens: "er frisst", praeteritum: "er fraß", perfekt: "er hat gefressen", translation: "dévorer, engloutir" },
  { infinitive: "frieren", praesens: "er friert", praeteritum: "er fror", perfekt: "er hat gefroren", translation: "geler" },
  { infinitive: "geben", praesens: "er gibt", praeteritum: "er gab", perfekt: "er hat gegeben", translation: "donner" },
  { infinitive: "gefallen", praesens: "es gefällt mir", praeteritum: "es gefiel mir", perfekt: "es hat mir gefallen", translation: "plaire" },
  { infinitive: "gehen", praesens: "er geht", praeteritum: "er ging", perfekt: "er ist gegangen", translation: "aller, marcher" },
  { infinitive: "gelingen", praesens: "es gelingt mir", praeteritum: "es gelang mir", perfekt: "es ist mir gelungen", translation: "réussir" },
  { infinitive: "gelten", praesens: "es gilt", praeteritum: "es galt", perfekt: "es hat gegolten", translation: "valoir" },
  { infinitive: "genießen", praesens: "er genießt", praeteritum: "er genoss", perfekt: "er hat genossen", translation: "apprécier, goûter" },
  { infinitive: "geschehen", praesens: "es geschieht", praeteritum: "es geschah", perfekt: "es ist geschehen", translation: "se produire" },
  { infinitive: "gewinnen", praesens: "er gewinnt", praeteritum: "er gewann", perfekt: "er hat gewonnen", translation: "gagner" },
  { infinitive: "gleichen", praesens: "er gleicht", praeteritum: "er glich", perfekt: "er hat geglichen", translation: "ressembler" },
  { infinitive: "gleiten", praesens: "er gleitet", praeteritum: "er glitt", perfekt: "er ist geglitten", translation: "glisser" },
  { infinitive: "graben", praesens: "er gräbt", praeteritum: "er grub", perfekt: "er hat gegraben", translation: "creuser" },
  { infinitive: "greifen", praesens: "er greift", praeteritum: "er griff", perfekt: "er hat gegriffen", translation: "saisir" },
  { infinitive: "halten", praesens: "er hält", praeteritum: "er hielt", perfekt: "er hat gehalten", translation: "tenir" },
  { infinitive: "hängen", praesens: "er hängt", praeteritum: "er hing", perfekt: "er hat gehangen", translation: "être accroché" },
  { infinitive: "heben", praesens: "er hebt", praeteritum: "er hob", perfekt: "er hat gehoben", translation: "lever, soulever" },
  { infinitive: "heißen", praesens: "er heißt", praeteritum: "er hieß", perfekt: "er hat geheißen", translation: "s’appeler" },
  { infinitive: "helfen", praesens: "er hilft", praeteritum: "er half", perfekt: "er hat geholfen", translation: "aider" },
  { infinitive: "kommen", praesens: "er kommt", praeteritum: "er kam", perfekt: "er ist gekommen", translation: "venir" },
  { infinitive: "laden", praesens: "er lädt", praeteritum: "er lud", perfekt: "er hat geladen", translation: "charger" },
  { infinitive: "lassen", praesens: "er lässt", praeteritum: "er ließ", perfekt: "er hat gelassen", translation: "laisser" },
  { infinitive: "laufen", praesens: "er läuft", praeteritum: "er lief", perfekt: "er ist gelaufen", translation: "courir" },
  { infinitive: "leiden", praesens: "er leidet", praeteritum: "er litt", perfekt: "er hat gelitten", translation: "souffrir" },
  { infinitive: "leihen", praesens: "er leiht", praeteritum: "er lieh", perfekt: "er hat geliehen", translation: "prêter" },
  { infinitive: "lesen", praesens: "er liest", praeteritum: "er las", perfekt: "er hat gelesen", translation: "lire" },
  { infinitive: "liegen", praesens: "er liegt", praeteritum: "er lag", perfekt: "er hat/ist gelegen", translation: "être couché" },
  { infinitive: "lügen", praesens: "er lügt", praeteritum: "er log", perfekt: "er hat gelogen", translation: "mentir" },
  { infinitive: "meiden", praesens: "er meidet", praeteritum: "er mied", perfekt: "er hat gemieden", translation: "éviter" },
  { infinitive: "messen", praesens: "er misst", praeteritum: "er maß", perfekt: "er hat gemessen", translation: "mesurer" },
  { infinitive: "nehmen", praesens: "er nimmt", praeteritum: "er nahm", perfekt: "er hat genommen", translation: "prendre" },
  { infinitive: "raten", praesens: "er rät", praeteritum: "er riet", perfekt: "er hat geraten", translation: "deviner" },
  { infinitive: "reißen", praesens: "er reißt", praeteritum: "er riss", perfekt: "er hat gerissen", translation: "déchirer, arracher" },
  { infinitive: "reiten", praesens: "er reitet", praeteritum: "er ritt", perfekt: "er ist geritten", translation: "faire du cheval" },
  { infinitive: "riechen", praesens: "er riecht", praeteritum: "er roch", perfekt: "er hat gerochen", translation: "sentir (une odeur)" },
  { infinitive: "rufen", praesens: "er ruft", praeteritum: "er rief", perfekt: "er hat gerufen", translation: "appeler" },
  { infinitive: "saufen", praesens: "er säuft", praeteritum: "er soff", perfekt: "er hat gesoffen", translation: "picoler" },
  { infinitive: "saugen", praesens: "er saugt", praeteritum: "er sog", perfekt: "er hat gesogen", translation: "aspirer" },
  { infinitive: "schaffen", praesens: "er schafft", praeteritum: "er schuf", perfekt: "er hat geschaffen", translation: "créer" },
  { infinitive: "scheiden", praesens: "er scheidet", praeteritum: "er schied", perfekt: "er hat geschieden", translation: "séparer" },
  { infinitive: "scheinen", praesens: "er scheint", praeteritum: "er schien", perfekt: "er hat geschienen", translation: "sembler, briller" },
  { infinitive: "scheißen", praesens: "er scheißt", praeteritum: "er schiss", perfekt: "er hat geschissen", translation: "faire ses besoins" },
  { infinitive: "schieben", praesens: "er schiebt", praeteritum: "er schob", perfekt: "er hat geschoben", translation: "pousser" },
  { infinitive: "schießen", praesens: "er schießt", praeteritum: "er schoss", perfekt: "er hat geschossen", translation: "tirer (sport, armes)" },
  { infinitive: "schlafen", praesens: "er schläft", praeteritum: "er schlief", perfekt: "er hat geschlafen", translation: "dormir" },
  { infinitive: "schlagen", praesens: "er schlägt", praeteritum: "er schlug", perfekt: "er hat geschlagen", translation: "frapper" },
  { infinitive: "schließen", praesens: "er schließt", praeteritum: "er schloss", perfekt: "er hat geschlossen", translation: "fermer" },
  { infinitive: "schmeißen", praesens: "er schmeißt", praeteritum: "er schmiss", perfekt: "er hat geschmissen", translation: "jeter, lancer" },
  { infinitive: "schneiden", praesens: "er schneidet", praeteritum: "er schnitt", perfekt: "er hat geschnitten", translation: "couper" },
  { infinitive: "schreiben", praesens: "er schreibt", praeteritum: "er schrieb", perfekt: "er hat geschrieben", translation: "écrire" },
  { infinitive: "schreien", praesens: "er schreit", praeteritum: "er schrie", perfekt: "er hat geschrien", translation: "crier" },
  { infinitive: "schreiten", praesens: "er schreitet", praeteritum: "er schritt", perfekt: "er ist geschritten", translation: "marcher, poser le pied" },
  { infinitive: "schweigen", praesens: "er schweigt", praeteritum: "er schwieg", perfekt: "er hat geschwiegen", translation: "se taire" },
  { infinitive: "schwimmen", praesens: "er schwimmt", praeteritum: "er schwamm", perfekt: "er ist geschwommen", translation: "nager" },
  { infinitive: "schwinden", praesens: "er schwindet", praeteritum: "er schwand", perfekt: "er ist geschwunden", translation: "diminuer" },
  { infinitive: "schwören", praesens: "er schwört", praeteritum: "er schwor", perfekt: "er hat geschworen", translation: "jurer (la vérité)" },
  { infinitive: "sehen", praesens: "er sieht", praeteritum: "er sah", perfekt: "er hat gesehen", translation: "voir" },
  { infinitive: "singen", praesens: "er singt", praeteritum: "er sang", perfekt: "er hat gesungen", translation: "chanter" },
  { infinitive: "sinken", praesens: "er sinkt", praeteritum: "er sank", perfekt: "er ist gesunken", translation: "couler" },
  { infinitive: "sitzen", praesens: "er sitzt", praeteritum: "er saß", perfekt: "er hat/ist gesessen", translation: "être assis" },
  { infinitive: "sprechen", praesens: "er spricht", praeteritum: "er sprach", perfekt: "er hat gesprochen", translation: "parler" },
  { infinitive: "springen", praesens: "er springt", praeteritum: "er sprang", perfekt: "er ist gesprungen", translation: "sauter" },
  { infinitive: "stehen", praesens: "er steht", praeteritum: "er stand", perfekt: "er hat/ist gestanden", translation: "être debout" },
  { infinitive: "stehlen", praesens: "er stiehlt", praeteritum: "er stahl", perfekt: "er hat gestohlen", translation: "dérober, voler" },
  { infinitive: "steigen", praesens: "er steigt", praeteritum: "er stieg", perfekt: "er ist gestiegen", translation: "monter" },
  { infinitive: "sterben", praesens: "er stirbt", praeteritum: "er starb", perfekt: "er ist gestorben", translation: "mourir" },
  { infinitive: "stinken", praesens: "er stinkt", praeteritum: "er stank", perfekt: "er hat gestunken", translation: "puer" },
  { infinitive: "stoßen", praesens: "er stößt", praeteritum: "er stieß", perfekt: "er hat gestoßen", translation: "heurter" },
  { infinitive: "(sich) streiten", praesens: "er streitet sich", praeteritum: "er stritt sich", perfekt: "er hat sich gestritten", translation: "se disputer" },
  { infinitive: "tragen", praesens: "er trägt", praeteritum: "er trug", perfekt: "er hat getragen", translation: "porter" },
  { infinitive: "treffen", praesens: "er trifft", praeteritum: "er traf", perfekt: "er hat getroffen", translation: "rencontrer" },
  { infinitive: "treiben", praesens: "er treibt", praeteritum: "er trieb", perfekt: "er hat getrieben", translation: "pratiquer" },
  { infinitive: "treten", praesens: "er tritt", praeteritum: "er trat", perfekt: "er hat/ist getreten", translation: "poser le pied, entrer" },
  { infinitive: "trinken", praesens: "er trinkt", praeteritum: "er trank", perfekt: "er hat getrunken", translation: "boire" },
  { infinitive: "tun", praesens: "er tut", praeteritum: "er tat", perfekt: "er hat getan", translation: "faire" },
  { infinitive: "umsteigen", praesens: "er steigt um", praeteritum: "er stieg um", perfekt: "er ist umgestiegen", translation: "changer (de véhicule)" },
  { infinitive: "vergehen", praesens: "es vergeht", praeteritum: "es verging", perfekt: "es ist vergangen", translation: "passer, s’écouler" },
  { infinitive: "vergessen", praesens: "er vergisst", praeteritum: "er vergaß", perfekt: "er hat vergessen", translation: "oublier" },
  { infinitive: "verlieren", praesens: "er verliert", praeteritum: "er verlor", perfekt: "er hat verloren", translation: "perdre" },
  { infinitive: "verstehen", praesens: "er versteht", praeteritum: "er verstand", perfekt: "er hat verstanden", translation: "comprendre" },
  { infinitive: "vorschlagen", praesens: "er schlägt vor", praeteritum: "er schlug vor", perfekt: "er hat vorgeschlagen", translation: "proposer" },
  { infinitive: "wachsen", praesens: "er wächst", praeteritum: "er wuchs", perfekt: "er ist gewachsen", translation: "grandir, augmenter" },
  { infinitive: "wägen", praesens: "er wägt", praeteritum: "er wog", perfekt: "er hat gewogen", translation: "peser (transitif)" },
  { infinitive: "waschen", praesens: "er wäscht", praeteritum: "er wusch", perfekt: "er hat gewaschen", translation: "laver" },
  { infinitive: "weichen", praesens: "er weicht", praeteritum: "er wich", perfekt: "er ist gewichen", translation: "céder, éviter" },
  { infinitive: "weisen", praesens: "er weist", praeteritum: "er wies", perfekt: "er hat gewiesen", translation: "indiquer, montrer" },
  { infinitive: "werben", praesens: "er wirbt", praeteritum: "er warb", perfekt: "er hat geworben", translation: "annoncer, promouvoir" },
  { infinitive: "werfen", praesens: "er wirft", praeteritum: "er warf", perfekt: "er hat geworfen", translation: "lancer, jeter" },
  { infinitive: "wiegen", praesens: "er wiegt", praeteritum: "er wog", perfekt: "er hat gewogen", translation: "peser" },
  { infinitive: "winden", praesens: "er windet", praeteritum: "er wand", perfekt: "er hat gewunden", translation: "enrouler" },
  { infinitive: "ziehen", praesens: "er zieht", praeteritum: "er zog", perfekt: "er hat gezogen", translation: "tirer" },
  { infinitive: "ziehen (partir)", praesens: "er zieht", praeteritum: "er zog", perfekt: "er ist gezogen", translation: "partir loin" },
  { infinitive: "zwingen", praesens: "er zwingt", praeteritum: "er zwang", perfekt: "er hat gezwungen", translation: "obliger, contraindre" }
];